package com.example.demo.dao.pojo;

import java.util.Date;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_kbn
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String areaKbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_name
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_name_en
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String areaNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.follow_area_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String followAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.detail_address
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String detailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.centerLon
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Double centerlon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.centerLat
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Double centerlat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.avg_pm25
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Integer avgPm25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.avg_pm10
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Integer avgPm10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.del_flg
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.version
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.create_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.create_time
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.update_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.update_time
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_kbn
     *
     * @return the value of area.area_kbn
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getAreaKbn() {
        return areaKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_kbn
     *
     * @param areaKbn the value for area.area_kbn
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setAreaKbn(String areaKbn) {
        this.areaKbn = areaKbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_name
     *
     * @return the value of area.area_name
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_name
     *
     * @param areaName the value for area.area_name
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_name_en
     *
     * @return the value of area.area_name_en
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getAreaNameEn() {
        return areaNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_name_en
     *
     * @param areaNameEn the value for area.area_name_en
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setAreaNameEn(String areaNameEn) {
        this.areaNameEn = areaNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.follow_area_id
     *
     * @return the value of area.follow_area_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getFollowAreaId() {
        return followAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.follow_area_id
     *
     * @param followAreaId the value for area.follow_area_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setFollowAreaId(String followAreaId) {
        this.followAreaId = followAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.detail_address
     *
     * @return the value of area.detail_address
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.detail_address
     *
     * @param detailAddress the value for area.detail_address
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.centerLon
     *
     * @return the value of area.centerLon
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Double getCenterlon() {
        return centerlon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.centerLon
     *
     * @param centerlon the value for area.centerLon
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setCenterlon(Double centerlon) {
        this.centerlon = centerlon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.centerLat
     *
     * @return the value of area.centerLat
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Double getCenterlat() {
        return centerlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.centerLat
     *
     * @param centerlat the value for area.centerLat
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setCenterlat(Double centerlat) {
        this.centerlat = centerlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.avg_pm25
     *
     * @return the value of area.avg_pm25
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Integer getAvgPm25() {
        return avgPm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.avg_pm25
     *
     * @param avgPm25 the value for area.avg_pm25
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setAvgPm25(Integer avgPm25) {
        this.avgPm25 = avgPm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.avg_pm10
     *
     * @return the value of area.avg_pm10
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Integer getAvgPm10() {
        return avgPm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.avg_pm10
     *
     * @param avgPm10 the value for area.avg_pm10
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setAvgPm10(Integer avgPm10) {
        this.avgPm10 = avgPm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.del_flg
     *
     * @return the value of area.del_flg
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.del_flg
     *
     * @param delFlg the value for area.del_flg
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.version
     *
     * @return the value of area.version
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.version
     *
     * @param version the value for area.version
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.create_id
     *
     * @return the value of area.create_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.create_id
     *
     * @param createId the value for area.create_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.create_time
     *
     * @return the value of area.create_time
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.create_time
     *
     * @param createTime the value for area.create_time
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.update_id
     *
     * @return the value of area.update_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.update_id
     *
     * @param updateId the value for area.update_id
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.update_time
     *
     * @return the value of area.update_time
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.update_time
     *
     * @param updateTime the value for area.update_time
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}