package com.example.demo.dao.mapper;

import com.example.demo.dao.pojo.Area;
import java.util.List;

public interface AreaMapper {
	/**
	 * 获取市级
	 */
	List<Area> getCitys();
	
	/**
	 * 获取区级
	 */
	List<Area> getAreas(String areaNo);
	
	
	/**
	 * 获取街道
	 */
	List<Area> getStreets(String streetNo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    Area selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    List<Area> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Mon Nov 19 11:28:06 CST 2018
     */
    int updateByPrimaryKey(Area record);
}